services:
  algolymptools:
    build:
        context: .
    image: "algolymptools:latest"
    container_name: "algolymptools"
    volumes:
      - ejudge_data:/home/judges:ro
    networks:
      - ejudge-net

volumes:
  ejudge_data:
    external: True

networks:
  ejudge-net:
    external: true
