services:
  algotools:
    build:
        context: .
    image: "algotools:latest"
    container_name: "algotools"
    volumes:
      - ejudge_data:/home/judges
    networks:
      - ejudge_net

volumes:
  ejudge_data:
    name: ejudge_data

networks:
  ejudge_net:
    name: ejudge_net
