services:
  algotools:
    build:
        context: .
    image: "algotools:latest"
    container_name: "algotools"
    volumes:
      - ejudge_data:/home/judges:ro
    networks:
      - ejudge-net

volumes:
  ejudge_data:
    external: True

networks:
  ejudge-net:
    external: true
